"""Emit a runnable equivalent of the request MemTriage would make.

The briefing is the analyst's data. Handing them a script that reproduces the
call — same system prompt, same caching, their key read from the environment
rather than embedded — means the conversation is not trapped inside this app, and
makes it obvious exactly what MemTriage sends and where.
"""
from __future__ import annotations

import json

from .context_pack import ContextPack
from .providers import ANTHROPIC, Provider, get_provider, resolve_base_url
from .service import ROLE_INSTRUCTIONS, build_system_prompt

BRIEFING_FILENAME = "memtriage_briefing.md"


def generate(pack: ContextPack, provider_id: str, model: str = "",
             base_url: str | None = None, language: str = "python") -> dict:
    provider = get_provider(provider_id)
    url = resolve_base_url(provider, base_url)
    chosen = model or provider.default_model
    if language == "curl":
        body = _curl(provider, url, chosen)
        filename = "memtriage_ask.sh"
    else:
        body = _python(provider, url, chosen)
        filename = "memtriage_ask.py"
    return {
        "provider": provider.id,
        "model": chosen,
        "language": language,
        "filename": filename,
        "briefing_filename": BRIEFING_FILENAME,
        "briefing": pack.markdown,
        "script": body,
        "instructions": _instructions(provider, language),
    }


def _instructions(provider: Provider, language: str) -> str:
    key_line = (f"export {provider.key_env}=... " if provider.key_env
                else "No API key needed for a local server. ")
    runner = "bash memtriage_ask.sh" if language == "curl" else "python memtriage_ask.py"
    install = ("pip install anthropic" if provider.transport == ANTHROPIC
               else "pip install openai")
    if language == "curl":
        install = "curl and jq"
    return (
        f"Save the briefing next to the script as {BRIEFING_FILENAME}. "
        f"{key_line}Then: {install}; {runner} \"your question\"."
    )


def _python(provider: Provider, base_url: str, model: str) -> str:
    key_env = provider.key_env or "UNUSED_API_KEY"
    fallback = '""' if not provider.key_env else "None"
    system_prefix = json.dumps(ROLE_INSTRUCTIONS)

    if provider.transport == ANTHROPIC:
        call = f'''
client = anthropic.Anthropic(api_key=API_KEY, base_url={base_url!r})

response = client.messages.create(
    model={model!r},
    max_tokens=8000,
    system=[{{
        "type": "text",
        "text": SYSTEM,
        # The briefing is stable across turns, so it is cached rather than
        # re-sent. usage.cache_read_input_tokens shows whether that worked.
        "cache_control": {{"type": "ephemeral"}},
    }}],
    messages=MESSAGES,
)

print("".join(b.text for b in response.content if b.type == "text"))
print(f"\\ncached input tokens: {{response.usage.cache_read_input_tokens}}", file=sys.stderr)
'''
        imports = "import anthropic"
    else:
        call = f'''
client = openai.OpenAI(api_key=API_KEY or "not-required", base_url={base_url!r})

response = client.chat.completions.create(
    model={model!r},
    max_tokens=8000,
    # The briefing goes first: providers with automatic prefix caching reuse it
    # across turns as long as these leading bytes do not change.
    messages=[{{"role": "system", "content": SYSTEM}}, *MESSAGES],
)

print(response.choices[0].message.content)
'''
        imports = "import openai"

    return f'''#!/usr/bin/env python3
"""Ask a question about a MemTriage investigation, outside MemTriage.

Generated by MemTriage. The briefing this reads is the same text the app sends;
your API key is read from the environment and is not written into this file.
"""
import os
import pathlib
import sys

{imports}

API_KEY = os.environ.get({key_env!r}) or {fallback}
BRIEFING = pathlib.Path(__file__).with_name({BRIEFING_FILENAME!r}).read_text()
SYSTEM = {system_prefix} + "\\n\\n---\\n\\n" + BRIEFING

question = " ".join(sys.argv[1:]) or "Summarize this investigation."
MESSAGES = [{{"role": "user", "content": question}}]
{call}'''


def _curl(provider: Provider, base_url: str, model: str) -> str:
    key_env = provider.key_env or "UNUSED_API_KEY"
    if provider.transport == ANTHROPIC:
        endpoint = f"{base_url}/v1/messages"
        auth = f'-H "x-api-key: ${key_env}" -H "anthropic-version: 2023-06-01"'
        payload = (
            '{model: $model, max_tokens: 8000, '
            'system: [{type: "text", text: $system, '
            'cache_control: {type: "ephemeral"}}], '
            'messages: [{role: "user", content: $question}]}'
        )
        extract = ".content[] | select(.type==\"text\") | .text"
    else:
        endpoint = f"{base_url}/chat/completions"
        auth = f'-H "Authorization: Bearer ${key_env}"'
        payload = (
            '{model: $model, max_tokens: 8000, messages: ['
            '{role: "system", content: $system}, '
            '{role: "user", content: $question}]}'
        )
        extract = ".choices[0].message.content"

    return f'''#!/usr/bin/env bash
# Ask a question about a MemTriage investigation, outside MemTriage.
# Generated by MemTriage. Requires curl and jq.
set -euo pipefail

QUESTION="${{*:-Summarize this investigation.}}"
BRIEFING="$(cat "$(dirname "$0")/{BRIEFING_FILENAME}")"
SYSTEM="$(cat <<'PROMPT'
{ROLE_INSTRUCTIONS}
PROMPT
)

---

$BRIEFING"

jq -n --arg model {model!r} --arg system "$SYSTEM" --arg question "$QUESTION" \\
  '{payload}' \\
| curl -sS {auth} \\
    -H "content-type: application/json" \\
    --data @- "{endpoint}" \\
| jq -r '{extract}'
'''
